name: Build MyST Gallery with Custom Filter Index

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          pip install pyyaml nbformat
          npm install -g mystmd

      - name: Generate static index.html with filtering
        run: python scripts/generate_gallery_html.py > index.html

      - name: Convert notebooks to HTML with myst
        run: myst build --html production/

      - name: Prepare deployment folder
        run: |
          mkdir -p full_site
          cp -r _build/html/* full_site/
          cp index.html full_site/index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: full_site

      - uses: actions/deploy-pages@v4
