name: Build MyST Gallery

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: pip install pyyaml mystmd

      - run: npm install -g mystmd

      - name: Generate static gallery index
        run: python scripts/generate_gallery_html.py > index.html

      - name: Build MyST HTML (notebooks only)
        run: myst build --html notebooks/

      - name: Prepare full_site folder
        run: |
          mkdir -p full_site
          cp -r _build/html/* full_site/
          cp index.html full_site/index.html  # ⬅️ wichtig! HTML-Galerie reinlegen

      - uses: actions/upload-pages-artifact@v3
        with:
          path: full_site

      - uses: actions/deploy-pages@v4
      - run: echo "✅ Your site is live at ${{ steps.deployment.outputs.page_url }}"
