name: MyST Deploy & Cookbook Integration

on:
  push:
    branches: [lol]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

env:
  BASE_URL: /${{ github.event.repository.name }}
  GALLERY_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          pip install pyyaml nbformat
          npm install -g mystmd

      - name: Build MyST HTML site
        run: myst build --html

      - name: Prepare full_site folder
        run: |
          mkdir -p full_site
          cp -r _build/html/* full_site/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: full_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
